import { COMPLIANCE } from "./constants";

export const Icons = {
  icons: {
    archive: "oj-ux-ico-archive",
    ProductManagement: "oj-ux-ico-search-list",
    itemWithoutBom: "oj-ux-ico-box",
    itemWithBom: "oj-ux-ico-application-suite",
    partGroup: "oj-ux-ico-ungroup",
    manufacturepart: "oj-ux-ico-bursting-definition",
    substance: "oj-ux-ico-beaker",
    substancegroup: "oj-ux-ico-beaker",
    material: "oj-ux-ico-ifc",
    subpart: "oj-ux-ico-data-segment",
    specification: "oj-ux-ico-file-doc-alt",
    declaration: "oj-ux-ico-artifact-audit-file",
    composition: "oj-ux-ico-taxonomy",
    exemption: "oj-ux-ico-download-error",
    smelter: "oj-ux-ico-bank",
    category: "oj-ux-ico-share",
    company: "oj-ux-ico-building",
    advancedSearch: "oj-ux-ico-content-item-search",
    reset: "oj-ux-ico-refresh",
    save: "oj-ux-ico-save",
    results: "oj-ux-ico-chart-table-edge-label",
    favourite: "oj-ux-ico-star-s",
    lock: "oj-ux-ico-lock",
    exportFile: "oj-ux-ico-file-excel-shortcut",
    create: "oj-ux-ico-plus",
    cross: "oj-ux-ico-close",
    check: "oj-ux-ico-check",
    multiply: "oj-ux-ico-multiply",
    edit: "oj-ux-ico-edit",
    delete: "oj-ux-ico-delete-all",
    deleteSelected: "oj-ux-ico-keep-selected",
    addColumns: "oj-ux-ico-add-column",
    reorderColumns: "oj-ux-ico-exchange-h",
    sort: "oj-ux-ico-sort-relevance-low",
    expandAll: "oj-ux-ico-expand",
    back: "oj-ux-ico-chevron-left",
    collapseAll: "oj-ux-ico-collapse",
    ascending: "oj-ux-ico-arrow-down",
    descending: "oj-ux-ico-arrow-up",
    importDeclaration: "oj-ux-ico-import",
    uploadFile: "oj-ux-ico-upload",
    downloadFile: "oj-ux-ico-download",
    pendingApprovals: "oj-ux-ico-assign-to-me",
    pendingRequests: "oj-ux-ico-defer",
    searches: "oj-ux-ico-search",
    jobs: "oj-ux-ico-progress-list",
    recentlyVisited: "oj-ux-ico-recent",
    users: "oj-ux-ico-contact-group",
    clearDataProvider: "oj-ux-ico-replay",
    generateReport: "oj-ux-ico-article-detail",
    updateUser: "oj-ux-ico-contact-edit",
    xml: "oj-ux-ico-file-xml",
    xlsx: "oj-ux-ico-file-excel",
    nextError: "oj-ux-ico-arrow-alt-down",
    previousError: "oj-ux-ico-arrow-alt-up",
    unknownSubs: "oj-ux-ico-information",
    adminPanel: "oj-ux-ico-user-configuration",
    resetPassword: "oj-ux-ico-reset-password",
    reports: "oj-ux-ico-profile-card",
    dossiers: "oj-ux-ico-folder-shared",
    submit: "oj-ux-ico-send",
    view: "oj-ux-ico-view",
    textFile: "oj-ux-ico-file-text",
    drawer: "oj-ux-ico-menu",
    home: "oj-ux-ico-home half",
    star: "oj-ux-ico-star half"
  },
  blockIcons: {
    generalInfo: "oj-ux-ico-page-header",
    aml: "oj-ux-ico-building",
    spec: "oj-ux-ico-artifact-audit-file",
    bom: "oj-ux-ico-data-grid-page-template",
    subsTab: "oj-ux-ico-beaker",
    exempTab: "oj-ux-ico-download-error",
    mpn: "oj-ux-ico-industry",
    affectedObjects: "oj-ux-ico-box-grid",
    attachments: " oj-ux-ico-attach-file",
    itemsWhereUsed: "oj-ux-ico-add-sibling",
    createNew: "oj-ux-ico-plus",
    selectAndAdd: "oj-ux-ico-new-version",
    smelterLookup: "oj-ux-ico-smart-filter-and-search-template",
    copyDeclaration: "oj-ux-ico-copy",
    selectAndAddMultipleSpecs: "oj-ux-ico-select-all",
    history: "oj-ux-ico-rearrange",
    attributes: "oj-ux-ico-brackets",
    sso: "oj-ux-ico-key",
    config: "oj-ux-ico-settings"
  },
  classes: {
    exportFileOption: "oj-ux-ico-copy oj-menu-item-icon",
    menuItem: "oj-menu-item",
    disable: "oj-disabled"
  }
}

export const ComplianceToIcon: Map<COMPLIANCE, string> = new Map([
  [COMPLIANCE.COMPLIANT, "oj-icon-color-success oj-ux-ico-success-s"],
  [COMPLIANCE.MISSINGINFO, "oj-icon-color-warning oj-ux-ico-help-circle-s"],
  [COMPLIANCE.NONCOMPLIANT, "oj-icon-color-danger oj-ux-ico-cancel-s"],
  [COMPLIANCE.EXEMPT, "oj-icon-color-info oj-ux-ico-success-s"],
  [COMPLIANCE.NOTAPPLICABLE, "oj-icon-color-info oj-ux-ico-help-circle-s"],
]);
