export const DefaultIcons = {
    addColumns: "oj-ux-ico-add-column",
    reorderColumns: "oj-ux-ico-exchange-h",
    exportFile: "oj-ux-ico-file-excel-shortcut",
    expandAll: "oj-ux-ico-expand",
    collapseAll: "oj-ux-ico-collapse",
    refresh: "oj-ux-ico-refresh",
    create: "oj-ux-ico-plus",
    delete: "oj-ux-ico-delete-all",
    deleteSelected: "oj-ux-ico-keep-selected",
    update: "oj-ux-ico-contact-edit",
    reset: "oj-ux-ico-reset-password",
    upload: "oj-ux-ico-upload",
    download: "oj-ux-ico-download",
}